library(plyr)
library(dplyr)

TP<-function(k,cutoff) {
  RRDR_gen <- read.csv(paste0("TBcohen_k",k,"_n1_p1_scores_RRDR_gen.csv", sep = ""),colClasses=c(rep("character",2),rep("numeric",5)))
  RRDR_gen <- unique(subset(RRDR_gen,select=c(1,3,4,5,6,7)))
  TBcohen_n1_p1_scores_gen <- read.csv(paste0("~/Dropbox/Research/GWAS/TBcohen_k",k,"_n1_p1_scores_gen.csv"),colClasses=c("character",rep("numeric",5)))
  rankGLS_pattern_gen<-TBcohen_n1_p1_scores_gen %>% filter(abs(rankGLS) < cutoff+1) %>% filter(abs(rankGLS) > 0) %>% select(pattern)
  rankLS_pattern_gen<-TBcohen_n1_p1_scores_gen %>% filter(abs(rankLS) < cutoff+1) %>% filter(abs(rankLS) > 0) %>% select(pattern)
  TP_LS<-intersect(rankLS_pattern_gen$pattern,RRDR_gen$pattern)
  TP_GLS<-intersect(rankGLS_pattern_gen$pattern,RRDR_gen$pattern)
  return(paste('LS:',length(TP_LS),'GLS:',length(TP_GLS)))
}

TP(17,10)
RRDR_gen <- read.csv(paste0("TBcohen_k",k,"_n1_p1_scores_RRDR_gen.csv", sep = ""),colClasses=c(rep("character",2),rep("numeric",5)))
RRDR_gen <- unique(subset(RRDR_gen,select=c(1,3,4,5,6,7)))
TBcohen_n1_p1_scores_gen <- read.csv(paste0("~/Dropbox/Research/GWAS/TBcohen_k",k,"_n1_p1_scores_gen.csv"),colClasses=c("character",rep("numeric",5)))
TBcohen_n1_p1_scores_cul <- read.csv(paste0("~/Dropbox/Research/GWAS/TBcohen_k",k,"_n1_p1_scores_cul.csv"),colClasses=c("character",rep("numeric",5)))
rankGLS_pattern_gen_10<-TBcohen_n1_p1_scores_gen %>% filter(abs(rankGLS) < 11) %>% filter(abs(rankGLS) > 0) %>% select(pattern)
rankGLS_pattern_gen_20<-TBcohen_n1_p1_scores_gen %>% filter(abs(rankGLS) < 21) %>% filter(abs(rankGLS) > 0) %>% select(pattern)
rankGLS_pattern_cul<-TBcohen_n1_p1_scores_cul %>% filter(abs(rankGLS) < 11) %>% filter(abs(rankGLS) > 0) %>% select(pattern)
rankLS_pattern_cul<-TBcohen_n1_p1_scores_cul %>% filter(abs(rankLS) < 11) %>% filter(abs(rankLS) > 0) %>% select(pattern)
rankLS_pattern_gen_10<-TBcohen_n1_p1_scores_gen %>% filter(abs(rankLS) < 11) %>% filter(abs(rankLS) > 0) %>% select(pattern)
rankLS_pattern_gen_20<-TBcohen_n1_p1_scores_gen %>% filter(abs(rankLS) < 21) %>% filter(abs(rankLS) > 0) %>% select(pattern)
TP_LS_10_k19<-intersect(rankLS_pattern_gen_10$pattern,RRDR_gen$pattern)
TP_LS_20_k19<-intersect(rankLS_pattern_gen_20$pattern,RRDR_gen$pattern)
TP_GLS_10_k19<-intersect(rankGLS_pattern_gen_10$pattern,RRDR_gen$pattern)
TP_GLS_20_k19<-intersect(rankGLS_pattern_gen_20$pattern,RRDR_gen$pattern)
intersect(TP_GLS_20_k17,TP_GLS_20_k19)
unique(TP_LS_10_k19)
inGLS<-setdiff(rankGLS_pattern_gen$pattern,rankLS_pattern_gen$pattern)
#OK, so there are 7 patterns that are in GLS_k17 but not LS_k17, but there are no kmers that are GLS_k17 and not LS_k17? This seems odd.
write.table(inGLS,file="GLSonly_k17.pattern", quote = F, row.names = F,col.names = F)
write.table(rankGLS_pattern_cul,file="rankGLS_k19_cul_1021.pattern", quote = F, row.names = F,col.names = F)
